export enum CODE_TYPE {
    FUNCTION = "FUNCTION",
    ARROW = "ARROW",
    CLASS_ARROW = "CLASS_ARROW",
    ARROW_METHOD = "ARROW_METHOD",
    METHOD = "METHOD",
    SVELTE_ARROW = "SVELTE_ARROW",
    SVELTE_FUNCTION = "SVELTE_FUNCTION",
}