export enum CODE_TYPE {
    FUNCTION = "FUNCTION",
    ARROW = "ARROW",
    CLASS_ARROW = "CLASS_ARROW",
    ARROW_METHOD = "ARROW_METHOD",
    METHOD = "METHOD",
    CUSTOM_EVENT_ARROW = "CUSTOM_EVENT_ARROW",
    CUSTOM_EVENT_FUNCTION = "CUSTOM_EVENT_FUNCTION",
    CUSTOM_EVENT_CLASS_ARROW = "CUSTOM_EVENT_CLASS_ARROW",
    CUSTOM_EVENT_ARROW_METHOD = "CUSTOM_EVENT_ARROW_METHOD",
}